// client/src/entities/invoice/ui/invoice-card/invoice-card.component.ts
import { Component, Input } from '@angular/core';
import { currencySymbols } from '../../constants/currencySymbols';
import { backgrounds } from '../../constants/cardBackgrounds';

@Component({
  selector: 'app-invoice-card',
  template: `
    <div
      class="p-16 border-radius-2 wp-200 hp-150 flex-col border-radius-8 gap-8"
      [ngClass]="backgrounds[invoiceType]"
    >
      <h3 class="caption-3">№{{ invoiceNumber }}</h3>
      <h2 class="subtitle-2">{{ name | slice: 0 : 10 }}...</h2>
      <div class="caption-2">
        Текущий баланс:
        <span class="headline"
        >{{ invoiceCount }}{{ currencySymbols[currency] }}</span
        >
      </div>
    </div>
  `,
})
export class InvoiceCardComponent {
  @Input({ required: true }) invoiceNumber!: number;

  @Input({ required: true }) invoiceCount!: number;

  @Input({ required: true }) currency!: string;

  @Input({ required: true }) name!: string;

  @Input({ required: true }) invoiceType!: string;

  protected readonly currencySymbols: Record<string, string> = currencySymbols;
  protected readonly backgrounds: Record<string, string> = backgrounds;
}

// frontend/src/entities/invoice/ui/InvoiceCard.tsx
import {currencySymbols} from "../constants/currencySymbols";
import {InvoiceCardProps} from "../model/types/InvoiceCardProps";

function InvoiceCard({
                         invoiceCount,
                         invoiceNumber,
                         currency,
                         invoiceType,
                         name,
                     }: InvoiceCardProps) {

    const backgrounds = {
        "MAIN": 'bg-main-card',
        "SAVINGS": "bg-saving-card",
        "INVEST": "bg-invest-card"
    }

    const truncateName = (name: string) => {
        if (name.length >= 14) {
            return name.slice(0, 13) + '...';
        }
        return name;
    }

    return (
        <div
            className={`p-16 border-radius-2 wp-200 hp-150 flex-col border-radius-8 gap-8 ${backgrounds[invoiceType]}`}>
            <h3 className="caption-3">
                №{invoiceNumber}
            </h3>
            <h2 className="subtitle-2">
                {truncateName(name as string)}
            </h2>
            <div className="caption-2">
                Текущий баланс: <span className="headline">{invoiceCount}{currencySymbols[currency]}</span>
            </div>
        </div>
    );
}

export default InvoiceCard;
