// client/src/widgets/layouts/page-layout/ui/page-layout.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-page-layout',
  standalone: true,
  template: `
    <section class="flex-col gap-34 mt-24 p-24 w-100 bg-white border-radius-8">
      <h1 class="subtitle-2">{{ title }}</h1>
      <ng-content></ng-content>
    </section>
  `,
})
export class PageLayoutComponent {
  @Input({ required: true }) title!: string;
}

// frontend/src/widgets/layouts/ui/PageLayout.tsx
import {PageLayoutProps} from "../model/types/PageLayoutProps";

function PageLayout({title, children}: PageLayoutProps) {
    return (
        <section className="flex-col gap-34 mt-24 p-24 w-100 bg-white border-radius-8">
            <h1 className="subtitle-2">{title}</h1>
            {children}
        </section>
    );
}

export default PageLayout;
