// client/src/proceses/auth/ui/login/login-form.component.ts
import { Component, inject } from '@angular/core';
import { CustomFormBuilder } from '../../../../shared/lib/services/custom-form-builder.service';
import { Validators } from '@angular/forms';
import { AuthService } from '../../api/services/auth.service';
import { LocalStorageService } from '../../../../shared/lib/services/localstorage.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login-form',
  templateUrl: 'login-form.component.html',
})
export class LoginFormComponent {
  public form = inject(CustomFormBuilder);

  private auth = inject(AuthService);
  private localStorage = inject(LocalStorageService);
  private router = inject(Router);

  public loginForm = this.form.group({
    login: ['', Validators.required],
    password: ['', Validators.required],
  });

  public enterAuth() {
    this.auth
      .login({
        identifier: this.loginForm.get('login')?.value as string,
        password: this.loginForm.get('password')?.value as string,
      })
      .subscribe(res => {
        this.localStorage.setItem('token', res.jwt);
        this.router.navigate(['/']);
      });
  }
}

<div>
  <div class="flex-col gap-10 mb-32">
    <h1 class="title">С возвращением!</h1>
<!--    <p class="caption-4 text-color">-->
<!--      We can assign tasks, set deadlines, and track progress effortlessly.-->
<!--    </p>-->
  </div>
  <form class="flex-col gap-32" [formGroup]="loginForm">
    <app-input
      type="text"
      label="Email или логин"
      placeholder="Введите логин/email"
      formControlName="login"
      [validation]="form.validation('login', loginForm)"></app-input>
    <app-input
      type="password"
      label="Пароль"
      placeholder="Введите пароль"
      formControlName="password"
      [validation]="form.validation('password', loginForm)"></app-input>

<!--    <span class="title-color text pointer">Забыли пароль ?</span>-->
    <app-button type="submit" [disabled]="loginForm.invalid" (click)="enterAuth()">Войти</app-button>
  </form>
</div>

// frontend/src/proceses/auth/ui/LoginForm.tsx
import {FC} from 'react';
import {Button, Input} from "../../../shared/ui";
import {Controller, useForm} from "react-hook-form";
import {AuthRequest} from "../model/types/AuthRequest.ts";
import {useMutation} from "@tanstack/react-query";
import {authUser} from "../api/authUser.ts";
import {useNavigate} from "react-router-dom";


const LoginForm: FC = () => {
    const navigate = useNavigate();

    const {control, handleSubmit} = useForm<AuthRequest>({
        defaultValues: {
            identifier: '',
            password: '',
        },
    });

    const mutation = useMutation({
        mutationFn: (formData: AuthRequest) => authUser(formData),
    });

    const onSubmit = (formData: AuthRequest) => {
        mutation.mutate(formData, {
            onSuccess: (data) => {
                localStorage.setItem('token', data.jwt);
                navigate('/');
            },
        });
    };

    return (
        <div>
            <div className="flex-col gap-10 mb-32">
                <h1 className="title">С возвращением!</h1>
                <p className="caption-4 text-color">We can assign tasks, set deadlines, and track progress
                    effortlessly.</p>
            </div>
            <form className="flex-col gap-32" onSubmit={handleSubmit(onSubmit)}>
                <Controller name="identifier" control={control} render={({field}) => (
                    <Input label="Имя пользователя" type="text" placeholder="Введите имя" {...field}/>
                )}/>

                <Controller
                    name="password"
                    control={control}
                    render={({field}) => (
                        <Input label="Пароль" type="password" placeholder="Введите пароль" {...field}/>
                    )}
                />

                <span className="title-color text pointer">Забыли пароль ?</span>
                <Button type="submit">Войти</Button>
            </form>
        </div>
    );
};

export default LoginForm;
