// frontend/src/shared/ui/button/Button.tsx
import {ButtonHTMLAttributes, FC, ReactNode} from 'react';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
    children?: ReactNode;
}

const Button: FC<ButtonProps> = ({children, ...props}) => {

    const bgColor = props.disabled ? 'bg-text' : 'bg-title'

    return (
        <button {...props} className={`p-19 border-radius-10 text-white subtitle-3 ${bgColor}`}>
            {children}
        </button>
    );
};

export default Button;

// client/src/shared/ui/button/button.component.ts
import { booleanAttribute, Component, Input } from '@angular/core';
import { NgClass } from '@angular/common';

@Component({
  selector: 'app-button',
  template: `
    <button
      class="p-19 border-radius-10 border-none w-100 text-white subtitle-3"
      [type]="type"
      [ngClass]="{ 'bg-text': disabled, 'bg-title': !disabled }"
      [disabled]="disabled"
    >
      <ng-content></ng-content>
    </button>
  `,
  standalone: true,
  imports: [NgClass],
})
export class ButtonComponent {
  @Input({ transform: booleanAttribute }) disabled = false;
  @Input() type: 'submit' | 'reset' | 'button' = 'button';
}
