// client/src/pages/history-page.component.ts
import { Component } from '@angular/core';
import { PageLayoutComponent } from '../widgets/layouts/page-layout/ui/page-layout.component';
import { RecordModule } from '../entities/record/record.module';

@Component({
  selector: 'app-history-page',
  template: `
    <app-page-layout title="История записей">
      <app-records-history></app-records-history>
    </app-page-layout>
  `,
  standalone: true,
  imports: [PageLayoutComponent, RecordModule],
})
export class HistoryPageComponent {}

// frontend/src/pages/HistoryPage.tsx
import HistoryRecordsTable from "../widgets/history-records/ui/HistoryRecordsTable";
import PageLayout from "../widgets/layouts/ui/PageLayout";

function HistoryPage() {
  return (
    <PageLayout title="История записей">
      <HistoryRecordsTable />
    </PageLayout>
  );
}

export default HistoryPage;
