// frontend/src/widgets/navbar/ui/Navbar.tsx
import {Input} from "../../../shared/ui";

type NavbarMethod = { openSidebar: () => void };

function Navbar({openSidebar}: NavbarMethod) {
    return (
        <nav className="flex ai-center jc-space p-25 gap-32">
            <div className="flex wp-250 jc-center ai-center gap-10 bg-white p-10 border-radius-5 shadow">
                <span className="title-3 pointer" onClick={openSidebar}>Planner</span>
            </div>
            <div className="w-100 bg-white flex ai-center gap-16 p-12 border-radius-5 shadow">
                <Input inputSize="small" placeholder="Поиск..." blockStyles="w-100"/>
                <img src="/img/person.png" alt="avatar"/>
            </div>
        </nav>
    );
}

export default Navbar;

// client/src/widgets/navbar/ui/navbar.component.ts
import {Component} from '@angular/core';
import {InputComponent} from "../../../shared/ui/input/input.component";

@Component({
  selector: 'app-navbar',
  template: `
    <nav class="flex ai-center jc-space p-25 gap-32">
      <div class="flex wp-250 jc-center ai-center gap-10 bg-white p-10 border-radius-5 shadow">
        <span class="title-3 pointer">Planner</span>
      </div>
      <div class="w-100 bg-white flex ai-center gap-16 p-12 border-radius-5 shadow">
        <app-input inputSize="small" placeholder="Поиск..." blockStyles="w-100" class="w-100"></app-input>
        <img src="/img/person.png" alt="avatar"/>
      </div>
    </nav>`,
  standalone: true,
  imports: [
    InputComponent
  ],
})

export class NavbarComponent {
}

<nav class="p-25 w-100">
  <div class="flex ai-center p-12 jc-space gap-32 border-radius-5 bg-white w-100 shadow">
    <div class="title-3">Planner</div>
<!--    <div class="flex ai-center gap-16">-->
<!--      <app-input-->
<!--        inputSize="small"-->
<!--        placeholder="Поиск..."-->
<!--      ></app-input>-->
<!--      <img src="/img/person.png" alt="avatar" />-->
<!--    </div>-->
  </div>
</nav>
